# ClickHouse Docker Compose Example
# Usage: docker-compose -f clickhouse.yml up -d
# Access ClickHouse client: docker exec -it dev-clickhouse clickhouse-client
# Access Web UI (Play): http://localhost:8123/play

version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: dev-clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse-config:/etc/clickhouse-server/config.d  # Optional: custom config
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
