[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:ybarsotti/nvim.git"
    refreshPeriod = "1h"
[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/themes/**"]
[".config/btop/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/btop/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/themes/**"]
[".config/git/catppuccin.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig"
    refreshPeriod = "168h"
