# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# cyberdream theme for lazygit
customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
gui:
    nerdFontsVersion: '3'
    border: rounded
    theme:
        activeBorderColor:
            - "#5ef1ff"
        inactiveBorderColor:
            - "#7b8496"
        searchingActiveBorderColor:
            - "#ff5ef1"
        optionsTextColor:
            - "#3c4048"
        selectedLineBgColor:
            - "#3c4048"
        cherryPickedCommitBgColor:
            - "#3c4048"
        cherryPickedCommitFgColor:
            - "#ff5ea0"
        unstagedChangesColor:
            - "#ffbd5e"
        defaultFgColor:
            - "#ffffff"
os:
  editPreset: 'vi'
  editInTerminal: true
