# vim: ft=tmux
# catppuccin config
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# date_time
set -ga status-right "#[fg=#{@thm_lavender}]"
set -ga status-right "#{?#{e|>:#{window_width},80},"
set -ga status-right " 󰃰 %Y-%m-%d %H:%M "
set -ga status-right ","
set -ga status-right " 󰃰 "
set -ga status-right "}"

set -agF status-right "#{E:@catppuccin_status_battery}"
